xspeed = 0;     // NOTE: all variables changable later   
yspeed = 0;
gravitystrength = 0.3;     
walkspeed = 10;     
jumpheight = -4;
animwalkspeed = 1;
animidlespeed = 1;
animpunchspeed = 1;
mask_index = spr_player_idle_side; // prevents clipping from the punch animation